version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app_pint
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8880:8880"
    networks:
      - laravel_network

networks:
  laravel_network:
