#!/bin/sh
# Don't panic with this file it was created for take git pre-commit hook by using laravel pint. 
# This File comes form .git/hooks to larvel root directory
# its putted here as backup


commit_message=$(git log -1 --pretty=format:%s)

# Check the operating system
if [[ "$OSTYPE" == "msys" || "$OSTYPE" == "win32" ]]; then
  # Windows
exec php vendor/bin/pint 
else
  # Unix-like (Linux and macOS)
  ./vendor/bin/pint && git add . && echo "Commit Message: $commit_message"
fi
echo "ijoin"
# Add changes to the staging area (git add)
git add .

git commit -m "$commit_message"